# Generated by Django 5.0.6 on 2024-06-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=128),
        ),
    ]
